---
- name: make raspi filesystem readable
  remote_user: pi
  hosts: raspi

  tasks:
          - name: check if overlay file exists
            find:
                    paths: /boot/
                    patterns: 'initrd.img-*-overlay'
                    recurse: no
            register: find_result

          - name: disable overlay filesystem
            become: true
            command: raspi-config nonint disable_overlayfs
            args:
                    removes: /boot/initrd.img-*-overlay
            when: find_result.matched > 0

          - name: reboot remote system
            become: true
            reboot:
                    reboot_timeout: 600
            when: find_result.matched > 0
